### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by defenddream** [stevewongv/DSC-PyTorch#7]
您好！请问UCF数据可以从哪里下载?模型在SBU数据集上测试正常，想看在UCF数据集上的效果，但是在网上找了很久也没有找UCF-shadow数据集，特来请教。

**Comment by stevewongv** [comment]
我现在也下载不到，可以试试发邮件给那篇文章的作者。

**Comment by defenddream** [comment]
好的，谢谢！

**Comment by HEXIAOHAO1993** [comment]
你现在找到了吗？

**Comment by JustinhoCHN** [comment]
@defenddream 请问预训练权重您可以用网盘再分享下吗？作者的这个权重的链接已经失效下不了了，谢谢。

**Comment by GuLicheng** [comment]
> 您好！请问UCF数据可以从哪里下载?模型在SBU数据集上测试正常，想看在UCF数据集上的效果，但是在网上找了很久也没有找UCF-shadow数据集，特来请教。

请问您找到UCF数据集了吗

**Comment by HEXIAOHAO1993** [comment]
MIMT公布的结果有UCF数据集 ---- 回复的原邮件 ***@***.***>发送日期2021年05月31日 17:03 ***@***.***> ***@***.******@***.***>主题Re: [stevewongv/DSC-PyTorch] 数据集问题 (#7)



您好！请问UCF数据可以从哪里下载?模型在SBU数据集上测试正常，想看在UCF数据集上的效果，但是在网上找了很久也没有找UCF-shadow数据集，特来请教。



请问您找到UCF数据集了吗



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/stevewongv/DSC-PyTorch/issues/7#issuecomment-851340675",

"url": "https://github.com/stevewongv/DSC-PyTorch/issues/7#issuecomment-851340675",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by GuLicheng** [comment]
> MIMT公布的结果有UCF数据集 ---- 回复的原邮件 ***@***.***>发送日期2021年05月31日 17:03 ***@***.***> ***@***.******@***.***>主题Re: [stevewongv/DSC-PyTorch] 数据集问题 (#7) 您好！请问UCF数据可以从哪里下载?模型在SBU数据集上测试正常，想看在UCF数据集上的效果，但是在网上找了很久也没有找UCF-shadow数据集，特来请教。 请问您找到UCF数据集了吗 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#7 (comment)](https://github.com/stevewongv/DSC-PyTorch/issues/7#issuecomment-851340675)", "url": "[#7 (comment)](https://github.com/stevewongv/DSC-PyTorch/issues/7#issuecomment-851340675)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

您好，我这里显示的是乱码，可以再发送一遍吗？
